/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author unicomer
 */
public class VentanaPago extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPago
     */
    public VentanaPago() {
        initComponents();    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        RdTardCred = new javax.swing.JRadioButton();
        RdSINPE = new javax.swing.JRadioButton();
        RdEfectivo = new javax.swing.JRadioButton();
        MontoaPag = new javax.swing.JTextField();
        MontoDeV = new javax.swing.JTextField();
        MontoCPag = new javax.swing.JTextField();
        LblMC = new javax.swing.JLabel();
        LblMP = new javax.swing.JLabel();
        LblVCl = new javax.swing.JLabel();
        BtnCobrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(RdTardCred);
        RdTardCred.setText("Tarjeta de Credito");

        buttonGroup1.add(RdSINPE);
        RdSINPE.setText("SINPE");

        buttonGroup1.add(RdEfectivo);
        RdEfectivo.setText("Efectivo");
        RdEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdEfectivoActionPerformed(evt);
            }
        });

        MontoaPag.setEnabled(false);
        MontoaPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MontoaPagActionPerformed(evt);
            }
        });

        MontoDeV.setEditable(false);
        MontoDeV.setEnabled(false);
        MontoDeV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MontoDeVActionPerformed(evt);
            }
        });

        MontoCPag.setEnabled(false);

        LblMC.setText("Monto a Cobrar");
        LblMC.setEnabled(false);

        LblMP.setText("Monto Pagado");
        LblMP.setEnabled(false);

        LblVCl.setText("Vuelto del Cliente");
        LblVCl.setEnabled(false);

        BtnCobrar.setText("Cobrar");
        BtnCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCobrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RdEfectivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RdSINPE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RdTardCred, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MontoaPag)
                    .addComponent(MontoDeV)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblVCl)
                            .addComponent(LblMP)
                            .addComponent(LblMC)))
                    .addComponent(MontoCPag))
                .addGap(18, 18, 18)
                .addComponent(BtnCobrar, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(RdTardCred)
                .addGap(18, 18, 18)
                .addComponent(RdSINPE)
                .addGap(18, 18, 18)
                .addComponent(RdEfectivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblMC)
                .addGap(4, 4, 4)
                .addComponent(MontoaPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblMP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MontoCPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblVCl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MontoDeV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCobrar))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MontoDeVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MontoDeVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MontoDeVActionPerformed

    private void MontoaPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MontoaPagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MontoaPagActionPerformed
/**
 * Este metodo hace la validacion de si el radio button de efectivo esta seleccionado o no 
 */
    private void RdEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdEfectivoActionPerformed
        // TODO add your handling code here:
        if(RdEfectivo.isSelected()){
        LblMC.setEnabled(true);
        MontoaPag.setEnabled(true);
        LblMP.setEnabled(true);
        MontoCPag.setEnabled(true);
        LblVCl.setEnabled(true);
        MontoDeV.setEnabled(true);
        
        }
        else{
        LblMC.setEnabled(false);
        MontoaPag.setEnabled(false);
        LblMP.setEnabled(false);
        MontoCPag.setEnabled(false);
        LblVCl.setEnabled(false);
        MontoDeV.setEnabled(false);
        }
    }//GEN-LAST:event_RdEfectivoActionPerformed

    private void BtnCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCobrarActionPerformed
        // TODO add your handling code here:
        CalculoVuelto();
    }//GEN-LAST:event_BtnCobrarActionPerformed
/**
 * Este metodo realiza el calculo del vuelto del cliente  
 */
    public void CalculoVuelto() {
        try {
            int NumCobro = Integer.parseInt(MontoaPag.getText());
            int NumPagado = Integer.parseInt(MontoCPag.getText());

            int VueltoCliente = NumPagado - NumCobro;
            
            MontoDeV.setText(String.valueOf(VueltoCliente));

        }
        catch (NumberFormatException e) {
        MontoDeV.setText("Error: Ingrese números válidos");
    }
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCobrar;
    private javax.swing.JLabel LblMC;
    private javax.swing.JLabel LblMP;
    private javax.swing.JLabel LblVCl;
    private javax.swing.JTextField MontoCPag;
    private javax.swing.JTextField MontoDeV;
    private javax.swing.JTextField MontoaPag;
    private javax.swing.JRadioButton RdEfectivo;
    private javax.swing.JRadioButton RdSINPE;
    private javax.swing.JRadioButton RdTardCred;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    // End of variables declaration//GEN-END:variables
}
