/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.util.prefs.Preferences;
import javax.swing.JOptionPane;
/**
 *
 * @author victorvf
 */
public class VentanaMeseroPed extends javax.swing.JFrame {
    
    VentanaMeseroMe VerMe = new VentanaMeseroMe();
    private int contadorPedidos = 0;
    
    /**
     * Creates new form VentanaEmpleado
     */
    public VentanaMeseroPed() {
        cargarEstConta();
        initComponents();
        
       try {
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            BufferedReader br = new BufferedReader(new FileReader("MenuComida.txt"));
            String line;
            while ((line = br.readLine()) != null) {
                String[] values = line.split(",");
                for (String value : values) {
                    model.addElement(value);
                }
            }
            br.close();
            PedidoCo.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
       try {
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            BufferedReader br = new BufferedReader(new FileReader("MenuBebidas.txt"));
            String line;
            while ((line = br.readLine()) != null) {
                String[] values = line.split(",");
                for (String value : values) {
                    model.addElement(value);
                }
            }
            br.close();
            PedidoBeb.setModel(model);
        } catch (Exception e2) {
            e2.printStackTrace();
        }
       
       try {
            ReadMesasDisponibles();
        } catch (Exception e2) {
            e2.printStackTrace();
        }
    }
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PedidoCo = new javax.swing.JComboBox<>();
        PedidoBeb = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        ModComida = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        ModBebida = new javax.swing.JTextArea();
        EnvPedido = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ConfirmPed = new javax.swing.JTextArea();
        Vmesas = new javax.swing.JButton();
        CmbNmesasD = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PedidoCo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        PedidoCo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PedidoCoMouseClicked(evt);
            }
        });
        PedidoCo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PedidoCoActionPerformed(evt);
            }
        });

        PedidoBeb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ModComida.setColumns(20);
        ModComida.setRows(5);
        jScrollPane3.setViewportView(ModComida);

        ModBebida.setColumns(20);
        ModBebida.setRows(5);
        jScrollPane4.setViewportView(ModBebida);

        EnvPedido.setText("Enviar");
        EnvPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnvPedidoActionPerformed(evt);
            }
        });

        ConfirmPed.setColumns(20);
        ConfirmPed.setRows(5);
        jScrollPane1.setViewportView(ConfirmPed);

        Vmesas.setText("Ver Mesas");
        Vmesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VmesasActionPerformed(evt);
            }
        });

        CmbNmesasD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PedidoCo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(PedidoBeb, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Vmesas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EnvPedido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CmbNmesasD, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PedidoBeb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PedidoCo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EnvPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Vmesas))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CmbNmesasD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PedidoCoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PedidoCoActionPerformed
        // TODO add your handling code here:    
    }//GEN-LAST:event_PedidoCoActionPerformed

    private void PedidoCoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PedidoCoMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_PedidoCoMouseClicked

    private void EnvPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnvPedidoActionPerformed
        // TODO add your handling code here: 
    contadorPedidos++;
    String ComidaSelec = PedidoCo.getSelectedItem().toString();
    String BebidaSelec = PedidoBeb.getSelectedItem().toString();
    String DeComida = ModComida.getText();
    String DeBebida = ModBebida.getText();
    String NmesaSelec = CmbNmesasD.getSelectedItem().toString();
 

    String contenido = "Pedido#"+ contadorPedidos + 
                       "\nComida: " + ComidaSelec + 
                       "\nBebida: " + BebidaSelec +
                       "\nDetalles de comida: " + DeComida + 
                       "\nDetalles de bebida: " + DeBebida +
                       "\nNumero de mesa: "+ NmesaSelec +
                       "\n  ";
    String archivoSalida = "PedidoCocina.txt";

    try {
        BufferedWriter writer = new BufferedWriter(new FileWriter(archivoSalida, true)); 
        writer.write(contenido);
        writer.newLine();
        writer.close();
        ConfirmPed.setText("Pedido#"+ contadorPedidos + " enviado");
        
    } catch (Exception e) {
        e.printStackTrace();
    }
       try {
        eliminarMesaSeleccionada();
        
    } catch (IOException e) {
        e.printStackTrace();
    }
    
    guardarEstConta();
    }//GEN-LAST:event_EnvPedidoActionPerformed

    private void VmesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VmesasActionPerformed
        // TODO add your handling code here:
        VerMe.setVisible(true);
        
    }//GEN-LAST:event_VmesasActionPerformed
    private void cargarEstConta() {
        Preferences Pre = Preferences.userNodeForPackage(VentanaMeseroPed.class);
        contadorPedidos = Pre.getInt("contadorPedidos", 0);
    }

    private void guardarEstConta() {
        Preferences Pre = Preferences.userNodeForPackage(VentanaMeseroPed.class);
        Pre.putInt("contadorPedidos",contadorPedidos);
    }
    
     private void ReadMesasDisponibles() throws IOException {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        BufferedReader br = new BufferedReader(new FileReader("NmesasDis.txt"));
        String line;
        while ((line = br.readLine()) != null) {
            String[] values = line.split(",");
            for (String value : values) {
                model.addElement(value);
            }
        }
        br.close();
        CmbNmesasD.setModel(model);
    }
     
    private void eliminarMesaSeleccionada() throws IOException {
    String mesaSeleccionada = CmbNmesasD.getSelectedItem().toString();

    
    File archivoOcu = new File("NmesasOcu.txt");
    BufferedReader brOcu = new BufferedReader(new FileReader(archivoOcu));
    String lineaOcu;
    boolean mesaExistente = false;
    while ((lineaOcu = brOcu.readLine()) != null) {
        if (lineaOcu.equals(mesaSeleccionada)) {
            mesaExistente = true;
            break;
        }
    }
    brOcu.close();

    if (mesaExistente) {
        JOptionPane.showMessageDialog(null,"La mesa seleccionada ya está ocupada");
        return;
    }

    List<String> mesasActualizadas = new ArrayList<>();

    File archivoDis = new File("NmesasDis.txt");
    BufferedReader br = new BufferedReader(new FileReader(archivoDis));
    String linea;
    while ((linea = br.readLine()) != null) {
        if (!linea.equals(mesaSeleccionada)) {
            mesasActualizadas.add(linea);
        }
    }
    br.close();

    BufferedWriter bw = new BufferedWriter(new FileWriter(archivoDis));
    for (String mesa : mesasActualizadas) {
        bw.write(mesa);
        bw.newLine();
    }
    bw.close();

    BufferedWriter bwOcu = new BufferedWriter(new FileWriter(archivoOcu, true));
    bwOcu.write(mesaSeleccionada);
    bwOcu.newLine();
    bwOcu.close();
    VerMe.actualizarComboBoxMesasOcu();

    ReadMesasDisponibles();
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMeseroPed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMeseroPed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMeseroPed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMeseroPed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMeseroPed().setVisible(true);
                VentanaMeseroPed Ven = new VentanaMeseroPed();
                Runtime.getRuntime().addShutdownHook(new Thread(() -> {
                Ven.guardarEstConta();
                }));
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbNmesasD;
    private javax.swing.JTextArea ConfirmPed;
    private javax.swing.JButton EnvPedido;
    private javax.swing.JTextArea ModBebida;
    private javax.swing.JTextArea ModComida;
    private javax.swing.JComboBox<String> PedidoBeb;
    private javax.swing.JComboBox<String> PedidoCo;
    private javax.swing.JButton Vmesas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables

    

}

